### ISSUE TITLE
Feature requests for enhanced nuxt generate options

### ISSUE THREAD

**Issue by dev7ch** [reallifedigital/nuxt-image-loader-module#5]
In my current work around I am having a static website after running `yarn build && yarn generate`

in my `<template>` i have:
  
`
<nuxt-img class="gallery-item-image" style="background: url('/loader.svg')" :src="child.image.replace('/uploads/', '/')" image-style="small" :alt="child.title" />
`

in my `<script>` is:
  
```js
created() {
      if (this.$store.state.menu) {
        for (let i = 0; i < this.$store.state.menu.length; ++i) {
          let menuParent = this.$store.state.menu[i].children
          for (let n = 0; n < menuParent.length; ++n) {

            if (menuParent[n].attributes.cover) {
              let attrs = menuParent[n]
              let img = menuParent[n].attributes.cover
              let cat = menuParent[n].attributes.gallery.gallery_cat
              let filename = img.substring(img.lastIndexOf('/') + 1);
              let menuThumb;

              console.log(filename)

              if (process.browser && !process.static) {
                menuThumb = '/' + filename + '?style=thumbnail'
              } else {
                menuThumb = '/image-styles/' + filename.substring(0, filename.lastIndexOf(".")) + "--thumbnail" + filename.substring(filename.lastIndexOf("."));
              }

              this.coverCats.indexOf(cat) > -1 ? null : this.coverCats.push(cat)

              this.coverItems.push({
                id: menuThumb.id,
                image: menuThumb,
                data: attrs
              })

              console.log(menuThumb)
            }
          }
        }
      }
    }
```

This an above a not well-working hack, how you can get it working for `nuxt generate` by changing around `if (process.browser && !process.static)` and run build and commit it to git.

... but it´s not 💯 nice ;)

So, my question is, is there any options to trigger the generation of images on `nuxt build`  or `nuxt generate`?

maybe by adding a post request to the URL? 
or sth in `store/index.js` at `nuxtServerInit`?

as it looks now I have to visit the page to trigger generation.

btw thank you for the super docs and clear git repo :)
and maybe if I understand better the generate trigger I could try to help with this implementation.

Cheers

**Comment by barryrld** [comment]
Hi @dev7ch 

It looks like your workaround is doing some heavy lifting towards the image generation. Ideally, we'd get this working with nuxt-image-loader-module natively so you don't have to handle both the node server versus generate versions.

At the moment, I can only see part of your implementation so I can make a few guesses.

It's possible that the `<nuxt-img>` component is only picking up on the initial render and doesn't detect when the state changes.

For the node server (i.e. `npm run build && npm run start`) the images are not optimistically loaded ahead of time, which is why you'll see the serverMiddleware intercepts image requests on the server, detects whether the image exists at the path in your `imagesBaseDir` and whether there is work to do to process the image with graphicsmagick (i.e. if there isn't a cached version on disk) and then finally serve the image directly. This is done in the `imageLoaderHandler` function in `index.js`.

For `npm run generate`, we need to know ahead of time which images to process. When `nuxt generate` runs there is a global array set up on `process.$imageLoaderRegistry`. Then each time the `<nuxt-img>` is rendered with the `render` lifecycle hook the `src` is added (in the query format) to this 'registry'. At the end of nuxt's generate process, this module registers an event to fire on `generate:done` which takes all images in the registry and performs all the necessary image generations and places them in `dist/image-styles/`. Also the `<nuxt-img>` knows to point the resulting `src` to the statically generated file relative to the currently viewed page.

That's it, in a nutshell, however, I appreciate the two paths for static and dynamic generation are quite different, but necessarily so, I think.

In summary, I would be great if we can work together so I can first fully understand what's tripping up in your case especially as there are no tests yet for anything more complex than referencing images in the `<nuxt-img>` component. What would be great is to get a working repo up and running which replicates the bug you're experiencing with the minimal amount of implementation details. Then we can use this as a test case for this module alongside the existing ones.

Another thought I had is that it may not be possible with `nuxt generate` to always know ahead of time (during the component's render) which images will be loaded. In this case, I could add a feature where you could define a glob pattern in your nuxt config file to always process certain (or all) images for particular image styles. Just a thought, although this might be nice as a catch-all. I'm not sure if this is needed right now and it would be good to get to the bottom of the underlying issue first.

Would you be able to share more of the code which represents the problem? Are you working on a public repo or is this a private project? Feel free to email me: barry [dot] fisher [at] reallifedigital.com

Thanks for your input,

Barry

**Comment by dev7ch** [comment]
Thank you @barryrld  for the detailed answer.

Yes, the code is public and I very appreciate your open attitude.

https://github.com/dev7ch/eloisa-florido-navarro.com/tree/nuxt-img-loader

You can see a demo here: https://festive-hypatia-797f57.netlify.com/

I ve set up a bit "broken use case",  where locally and renderd all works fine.

But finally, i got it almost working. 
Please see the Mainnav "Arbeiten" the submenu is a working example in the Sub Menu

In [Line #66](https://github.com/dev7ch/eloisa-florido-navarro.com/blob/nuxt-img-loader/components/MainNav.vue#L66) is where `<nuxt-img>` is implemted.

The first 4 thumbnails are your module, the other ones a kind of hybrid with another module.


Is this good for you as a replica dev repo to work together?
Or should we start with a clean one?

**Comment by dev7ch** [comment]
Just to summarize your input up according to the usecas in the replica:


#### Status Quo
- [x] ´<nuxt-img>´ component is only picking up on the initial render (static only?)
- [x] ´process.$imageLoaderRegistry´defines whats is beeing generated (on `generate:done`)
- [x] Then each time the <nuxt-img> is rendered with the render lifecycle hook the src (universal or dev process?)

Did I understand and check the boxes above correctly? 
.. the "?" in brackets mean I am not sure.
 

#### Workarounds/Requirements/Dreams:

- [  ] Find all images and trigger local resizeCrop programmatically (catch all)
- [x] Replace image source url on `process.static`
- [x] Find a solution the keep images outisde from Repo 
- [  ] Fetching source images from outside to local and static Server (e.g media server, cdn)
- [  ] Placeholder or Poster Property for component (and maybe fallback)
- [  ] Rerender and update images if resizeCrop settings changed
- [  ] Provide and carry Image Metadata (height, width, etc), store it somewhere
- [  ] Option to enable pre-generation of all images for certain styles



#### Complex  Challenges
- [  ] Create a file system map of all images on `yarn build` dynamic Img metadata
- [  ] Allow style to be "null" or overwritten by v-bind and update path accordingly
- [  ] Implement use of IntersectionObserver to handle big images and lazyLoading


... this came to my mind while dreaming about a perfect img loader, plz see this a brainstorming, not a tasklist :)

>  @barryrld  wrote: ... I could add a feature where you could define a glob pattern in your nuxt config file to always process certain (or all) images for particular image styles. 

Yes, yes, yes 👍 

> ... a catch-all. I'm not sure if this is needed right now and it would be good to get to the bottom of the underlying issue first.

That's was also my way of thinking, like "Doing the needed request on next build to all images"
I think it could be worth to consider adding this as an option for each style in `nuxt.config.js`

I hope this helps you and brings you fun.

**Comment by barryrld** [comment]
Hi @dev7ch,

Thanks for the detailed list. There's a lot to think about here, so I'll curate this list into sub-feature requests at some time later.

For now, I wanted to let you know about a new feature in the latest release v1.2.0.

There is now the ability to force generate certain images style given a glob pattern for those instances where you need to dynamically load images asyncronously. There's more details in the updated docs:

https://github.com/reallifedigital/nuxt-image-loader-module#do-you-need-to-lazy-load-images-when-running-nuxt-generate

I hope this allow you to make so further progress in your use case for now. I haven't had a chance to review your project repo just yet. Before I do, I wonder if you'd be able to try out the latest version of this module and try the new option in nuxt.config.js to see if this solves anything for you.

Thanks,

Barry

**Comment by dev7ch** [comment]
@barryrld thanks a lot for adding the very useful `forceGenerateImages`  in `nuxt.config.js`

**Comment by dev7ch** [comment]
@barryrld sorry for my late response, i am on holidays but tested it quickly and it works fine so far. Do you want me to close this issue or keep it open for the future enhancement?

btw thanks for adding the credentials in the readme file :)

**Comment by barryrld** [comment]
@dev7ch No problem!

I'll close this issue for now seen as the `forceGenerateImages` likely solve a lot of issues. I'd still like to revisit the possibility of pulling in external images in the future, however, this isn't a high priority for me at the moment.

Thanks, Barry
